- dudendown.py
Hi,
Here are 2 small patches:
+ Avoid warning and add a newline
+ Display "Wortart", which is very useful to know the gender of a noun
> Little improvements

- dudendown.py
This pull request doesn't introduce any new or change any existing functionality. Its whole purpose is to make the code more readable and compliant to the standard - pep8 in this case.
The `autopep8` tool makes it easy to keep the code compliant to the standard. It suggests you the changes by running
```
autopep8 --diff dudendown.py | colordiff
```
The `| colordiff` part is optional, it only makes the diff colored and easier to navigate through. The `-i` switch will make `autopep8` apply the changes to the file (not only display them).
> Clean up whitespace and comments

- dudendown.py
Functions have been moved to the beginning of the file and have been given docstrings.
A few comments were added to the code.
> Comments and docstrings update

- .gitignore
- .travis.yml
- Makefile
- Pipfile
- requirements.txt
> Manage dev requirements by pipenv

- duden/main.py
This switch allows to display different grammar forms/cases of a given
word.
Fixes #43.
> Add the -g/--grammar CLI switch

- setup.py
See https://packaging.python.org/tutorials/distributing-packages/#license
> Add license for Python package

- duden/main.py
> Fix bug with words without word type

- Makefile
- completions/duden
- completions/duden.fish
And two Makefile targets to install them
Fixes #56
> Add bash and fish shell completion

- duden/main.py
> Remove figure annotation text from meaning overview

- duden/search.py
Works on my machine, but needs to be verified on another one.
> fixed utf8 encoding error on windows

- tests/test_data/Barmherzigkeit.yaml
- tests/test_data/Feiertag.yaml
- tests/test_data/Petersilie.yaml
- tests/test_data/Qat.yaml
- tests/test_data/einfach.yaml
- tests/test_data/laufen.yaml
The duden data changed in the meantime, so the tests data must be changed as well.
Long-term, we should make tests that do not break with every small change in the source data.
> Fix online test data 2021-02-27

- Makefile
Goal is to be better focused during troubleshooting/polishing.
> Split test and linters check Makefile goal

- duden/word.py
> Fix name and article attributes for non-nouns

- duden/display.py
Such as auf_Praeposition
Fixes #114
> Fix displaying words with missing grammar

- duden/search.py
> Fix cache dir creation on Windows

- duden/search.py
> Handle error when cache is corrupt

- Makefile
- tests/test_data/Petersilie.yaml
- tests/test_data/Qat.yaml
- tests/test_data/laufen.yaml
- tests/test_online_attributes.py
> Update test data

- Makefile
- README.md
- duden/__init__.py
- duden/__version__.py
- duden/cli.py
- duden/common.py
- duden/constants.py
- duden/display.py
- duden/search.py
- duden/word.py
- pyproject.toml
- run_duden.py
- tests/test_online_attributes.py
To execute them, run 
```
make autoformat
```
in the poetry shell environment.
> Introduce isort and black autoformatters

- docs/usage.md
> Document the phonetic word property in usage.md

- CHANGELOG.md
- Makefile
- README.md
> Document the localization process

- duden/cli.py
> Silence pylint issue

- tests/test_data/Keyboard.yaml
Keyboard meaning overview changed.
> Fix online test data 2024-02-25
